import '../../app/[locale]/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navbar } from '@/components/navbar';
import { useLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import {NextIntlClientProvider} from 'next-intl';
import { AsyncLayout } from '@/app/[locale]/async-layout';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: Record<string, string>
}) {
  const locale = useLocale();
  if (params.locale !== locale) {
    // redirect to default
    notFound()
  }



  return (
    <html lang={locale}>
      <body className={inter.className}>
        <AsyncLayout locale={locale}>
          {children}
        </AsyncLayout>
      </body>
    </html>
  )
}
